In [1]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.3.1.tar.gz (281.4 MB)
Collecting py4j==0.10.9.5
  Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py): started
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): still running...
  Building wheel for pyspark (setup.py): finished with status 'done'
  Created wheel for pyspark: filename=pyspark-3.3.1-py2.py3-none-any.whl size=281845512 sha256=e984f9e98077d4c95e77b968f22989914ae6b4d56c75204da07bf3cd58f95159
  Stored in directory: c:\users\ehtisham raza\appdata\local\pip\cache\wheels\51\c8\18\298a4ced8ebb3ab8a7d26a7198c0cc7035abb906bde94a4c4b
Successfully built pyspark
Installing collected packages: py4j, pyspark
  Attempting uninstall: py4j
    Found existing installation: py4j 0.10.9.3
    Uninstalling py4j-0.10.9.3:
      Successfully uninstalled py4j-0.10.9.3
Successfully installed py4j-0.10.9.5 pyspark-3.3.1

In [2]:
import pyspark

In [3]:
import pandas as pd

In [4]:
pd.read_csv('file (1).csv')

    Sales     date genre
0   16.83  2009-01  Rock
1    6.93  2009-02  Rock
2    8.91  2009-03  Rock
3   21.78  2009-04  Rock
4    7.92  2009-05  Rock
5   15.84  2009-06  Rock
6   18.81  2009-07  Rock
7   19.80  2009-08  Rock
8    4.95  2009-09  Rock
9   19.80  2009-10  Rock
10  18.81  2009-11  Rock
11  17.82  2009-12  Rock
12   9.90  2010-01  Rock
13  20.79  2010-02  Rock
14   4.95  2010-03  Rock
15  13.86  2010-04  Rock
16   3.96  2010-05  Rock
17  12.87  2010-06  Rock
18  23.76  2010-07  Rock
19   6.93  2010-08  Rock
20  13.86  2010-09  Rock
21  15.84  2010-10  Rock
22  23.76  2010-11  Rock
23   4.95  2010-12  Rock
24  16.83  2011-01  Rock
25  23.76  2011-02  Rock
26  17.82  2011-03  Rock
27   5.94  2011-04  Rock
28  24.75  2011-05  Rock
29   4.95  2011-06  Rock
30  11.88  2011-07  Rock
31   2.97  2011-08  Rock
32  17.82  2011-09  Rock
33  17.82  2011-10  Rock
34   1.98  2011-11  Rock
35   9.90  2011-12  Rock
36  11.88  2012-01  Rock
37  27.72  2012-02  Rock
38   3.96  2012-03  Rock
39   7.92  2012-04  Rock
40  19.80  2012-05  Rock
41  20.79  2012-06  Rock
42  19.80  2012-07  Rock
43  25.74  2012-08  Rock
44   5.94  2012-09  Rock
45   3.96  2012-10  Rock
46   8.91  2012-11  Rock
47   5.94  2012-12  Rock
48   6.93  2013-01  Rock
49  16.83  2013-02  Rock
50   5.94  2013-03  Rock
51   9.90  2013-04  Rock
52  10.89  2013-05  Rock
53  21.78  2013-06  Rock
54   7.92  2013-07  Rock
55  16.83  2013-08  Rock
56  22.77  2013-09  Rock
57  17.82  2013-10  Rock
58   6.93  2013-11  Rock
59  29.70  2013-12  Rock

In [5]:
from pyspark.sql import SparkSession

In [6]:
spark = SparkSession.builder.appName('Practise').getOrCreate()

In [7]:
spark

In [8]:
df_pyspark = spark.read.csv('file (1).csv')

In [9]:
df_pyspark

DataFrame[_c0: string, _c1: string, _c2: string]

In [10]:
df_pyspark.show()

+-----+-------+-----+
|  _c0|    _c1|  _c2|
+-----+-------+-----+
|Sales|   date|genre|
|16.83|2009-01| Rock|
| 6.93|2009-02| Rock|
| 8.91|2009-03| Rock|
|21.78|2009-04| Rock|
| 7.92|2009-05| Rock|
|15.84|2009-06| Rock|
|18.81|2009-07| Rock|
| 19.8|2009-08| Rock|
| 4.95|2009-09| Rock|
| 19.8|2009-10| Rock|
|18.81|2009-11| Rock|
|17.82|2009-12| Rock|
|  9.9|2010-01| Rock|
|20.79|2010-02| Rock|
| 4.95|2010-03| Rock|
|13.86|2010-04| Rock|
| 3.96|2010-05| Rock|
|12.87|2010-06| Rock|
|23.76|2010-07| Rock|
+-----+-------+-----+
only showing top 20 rows

In [17]:
df_pyspark = spark.read.option('header','true').csv('file (1).csv')

In [18]:
df_pyspark

DataFrame[Sales: string, date: string, genre: string]

In [19]:
df_pyspark.head(4)

[Row(Sales='16.83', date='2009-01', genre='Rock'),
 Row(Sales='6.93', date='2009-02', genre='Rock'),
 Row(Sales='8.91', date='2009-03', genre='Rock'),
 Row(Sales='21.78', date='2009-04', genre='Rock')]

In [20]:
df_pyspark.printSchema()

root
 |-- Sales: string (nullable = true)
 |-- date: string (nullable = true)
 |-- genre: string (nullable = true)